"""Init: generate the universal profile skeleton for any character.

Usage:
    python3 init-universal-profile-skeleton.py <character-slug> [--display-name "Display Name"]

Creates the full 25-file nested structure under docs/profiles/<character-slug>/ with empty files
carrying mandatory YAML frontmatter. The structure mirrors paths.PROFILE_FILES (the single source of
truth for the universal schema): identity/psychology/relationships/timeline/darkness/light/evidence are
PSY-domain (stamped psy:wave, the build skill); growth/ is GRO-domain (stamped with its owning gro skill
so gro:validate's gro:* prefix check passes).
"""
import argparse
import sys
from pathlib import Path
from datetime import date

# Universal schema: same files for ALL characters, no exceptions. Must stay in sync with
# paths.PROFILE_FILES. Key = subdirectory (or "root" for top-level), Value = list of (filename, domain, type).
SCHEMA = {
    "root": [
        ("INDEX.md", "root", "index"),
        ("CURRENT-STATE.md", "root", "snapshot"),
        ("milestones.md", "root", "data"),
    ],
    "identity": [
        ("core.md", "identity", "narrative"),
        ("writing-voice.md", "identity", "analysis"),
        ("achievements.md", "identity", "data"),
        ("media-coverage.md", "identity", "data"),
    ],
    "psychology": [
        ("core-wounds.md", "psychology", "analysis"),
        ("defense-mechanisms.md", "psychology", "analysis"),
        ("attachment-style.md", "psychology", "analysis"),
        ("growth-edges.md", "psychology", "analysis"),
        ("formulation.md", "psychology", "analysis"),
        ("diagnostics.md", "psychology", "analysis"),
        ("cultural-formulation.md", "psychology", "analysis"),
        ("archetype.md", "psychology", "analysis"),
    ],
    "psychology/case-studies": [],
    "relationships": [
        ("family.md", "relationships", "narrative"),
    ],
    "timeline": [
        ("overview.md", "timeline", "data"),
        ("state-timeline.md", "timeline", "analysis"),
    ],
    "darkness": [
        ("traumas.md", "darkness", "analysis"),
    ],
    "light": [
        ("strengths-hope.md", "light", "analysis"),
    ],
    "evidence": [
        ("conversations.md", "evidence", "data"),
    ],
    # GRO-domain (Rule 15) — owns docs/profiles/*/growth/. Each file is stamped with its owning gro
    # skill so a freshly-scaffolded profile passes gro:validate's gro:* updated_by check.
    "growth": [
        ("career-path.md", "growth", "data"),
        ("competencies.md", "growth", "data"),
        ("learning-profile.md", "growth", "data"),
        ("mentoring-map.md", "growth", "data"),
    ],
}

# Provenance stamp per file. growth/ → its owning gro skill (satisfies gro:validate); everything else →
# psy:wave (the documented profile-build skill; matches the existing corpus convention).
GROWTH_OWNER = {
    "career-path.md": "gro:career-path",
    "competencies.md": "gro:competency-map",
    "learning-profile.md": "gro:learning-profile",
    "mentoring-map.md": "gro:mentoring-track",
}


def updated_by_for(subdir: str, fname: str) -> str:
    if subdir == "growth":
        return GROWTH_OWNER.get(fname, "gro:career-path")
    return "psy:wave"


INDEX_TEMPLATE = """# {display_name} — Profile Index

| Domain | File | Status |
|--------|------|--------|
{file_table}

> Generated by profile-init on {today}. Fill progressively.
"""

FRONTMATTER_TEMPLATE = """---
character: {slug}
domain: {domain}
type: {ftype}
tags: []
references: []
cross_characters: []
last_updated: {today}
updated_by: {updated_by}
confidence: unverified
---

# {title}

> Empty skeleton — awaiting content.
"""

CURRENT_STATE_TEMPLATE = """---
character: {slug}
domain: root
type: snapshot
tags: []
references: []
cross_characters: []
last_updated: {today}
updated_by: psy:wave
confidence: unverified
---

# {display_name} — Current State

**As of:** {today}

## Quick Summary

> Awaiting initial assessment.

## Current Phase

> Not yet determined. See `timeline/state-timeline.md`.

## Active Concerns

- None documented yet.

## Protective Factors Active

- None documented yet.
"""


def title_from_filename(filename: str) -> str:
    return filename.replace(".md", "").replace("-", " ").title()


def generate_index_table(slug: str) -> str:
    rows = []
    for subdir, files in SCHEMA.items():
        for fname, domain, ftype in files:
            path = fname if subdir == "root" else f"{subdir}/{fname}"
            rows.append(f"| {domain} | [{fname}]({path}) | empty |")
    return "\n".join(rows)


def create_skeleton(base_dir: Path, slug: str, display_name: str) -> int:
    today = date.today().isoformat()
    created = 0

    for subdir, files in SCHEMA.items():
        target_dir = base_dir if subdir == "root" else base_dir / subdir
        target_dir.mkdir(parents=True, exist_ok=True)

        for fname, domain, ftype in files:
            filepath = target_dir / fname
            if filepath.exists():
                print(f"  SKIP (exists): {filepath.relative_to(base_dir.parent.parent.parent)}")
                continue

            if fname == "INDEX.md":
                content = INDEX_TEMPLATE.format(
                    display_name=display_name,
                    file_table=generate_index_table(slug),
                    today=today,
                )
            elif fname == "CURRENT-STATE.md":
                content = CURRENT_STATE_TEMPLATE.format(
                    slug=slug,
                    display_name=display_name,
                    today=today,
                )
            else:
                content = FRONTMATTER_TEMPLATE.format(
                    slug=slug,
                    domain=domain,
                    ftype=ftype,
                    today=today,
                    title=title_from_filename(fname),
                    updated_by=updated_by_for(subdir, fname),
                )

            filepath.write_text(content, encoding="utf-8")
            created += 1
            print(f"  CREATE: {filepath.relative_to(base_dir.parent.parent.parent)}")

    return created


def main():
    parser = argparse.ArgumentParser(description="Init: generate universal profile skeleton")
    parser.add_argument("slug", help="Character slug (e.g., jane-q-doe)")
    parser.add_argument("--display-name", default=None, help="Display name (e.g., 'Jane Doe')")
    parser.add_argument("--project-root", default=None, help="Project root (auto-detected if omitted)")
    args = parser.parse_args()

    if args.project_root:
        root = Path(args.project_root)
    else:
        root = Path(__file__).resolve().parent.parent.parent

    profiles_dir = root / "docs" / "profiles"
    if not profiles_dir.exists():
        print(f"ERROR: {profiles_dir} not found. Are you in the right project?", file=sys.stderr)
        sys.exit(1)

    char_dir = profiles_dir / args.slug
    display_name = args.display_name or args.slug.replace("-", " ").title()

    print(f"Profile init: {args.slug} ({display_name})")
    print(f"  Target: {char_dir}")

    created = create_skeleton(char_dir, args.slug, display_name)
    print(f"\nDone. Created {created} files.")

    # Auto-register into the roster so a scaffolded character is NEVER unregistered (drift invariant).
    # Stub-only-if-absent: never clobbers an already-enriched characters.yaml entry. Best-effort —
    # a missing pyyaml must not fail the scaffold (the file writes above already succeeded).
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parent / "platform_lib"))
        import roster_io

        if roster_io.ensure_registered(args.slug, display_name, profiles_dir):
            print(f"Registered roster stub: {args.slug} -> characters.yaml")
            print("  Enrich aliases (display + full name + IME-typo variants) via profile-manager.")
        else:
            print(f"Roster entry already present for {args.slug} (left unchanged).")
    except Exception as e:  # pyyaml missing / write issue — surface, don't fail the scaffold
        print(f"WARN: roster auto-register skipped ({e}). Add {args.slug} to characters.yaml manually.",
              file=sys.stderr)


if __name__ == "__main__":
    main()
