#!/usr/bin/env python3
"""Generate empty DSM-5 MDD 9-criteria checklist markdown template for a character.
Pre-fills character name and date. Output is ready for LLM to fill in evidence."""
import os
import sys
import argparse
from datetime import date

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..', 'scripts'))
from platform_lib.paths import resolve_character, CHAR_DISPLAY

DSM5_MDD_CRITERIA = [
    (
        "A1",
        "Depressed mood most of the day, nearly every day",
        "Khí sắc trầm cảm phần lớn thời gian trong ngày, gần như mỗi ngày",
    ),
    (
        "A2",
        "Markedly diminished interest or pleasure in all/almost all activities",
        "Giảm rõ rệt hứng thú hoặc niềm vui trong hầu hết mọi hoạt động",
    ),
    (
        "A3",
        "Significant weight/appetite change (>5% body weight in a month)",
        "Thay đổi cân nặng/thèm ăn đáng kể (>5% trọng lượng cơ thể/tháng)",
    ),
    (
        "A4",
        "Insomnia or hypersomnia nearly every day",
        "Mất ngủ hoặc ngủ nhiều gần như mỗi ngày",
    ),
    (
        "A5",
        "Psychomotor agitation or retardation (observable by others)",
        "Kích động tâm vận động hoặc chậm chạp (người khác quan sát được)",
    ),
    (
        "A6",
        "Fatigue or loss of energy nearly every day",
        "Mệt mỏi hoặc mất năng lượng gần như mỗi ngày",
    ),
    (
        "A7",
        "Feelings of worthlessness or excessive/inappropriate guilt",
        "Cảm giác vô giá trị hoặc tội lỗi quá mức / không thích hợp",
    ),
    (
        "A8",
        "Diminished ability to think/concentrate or indecisiveness",
        "Giảm khả năng suy nghĩ/tập trung hoặc thiếu quyết đoán",
    ),
    (
        "A9",
        "Recurrent thoughts of death, suicidal ideation, or attempt",
        "Suy nghĩ tái diễn về cái chết, ý tưởng tự tử, hoặc mưu toan tự tử",
    ),
]

TEMPLATE_HEADER = """\
# DSM-5 Major Depressive Disorder (MDD) Checklist
## Character: {character}
## Date: {date}
## Status: DRAFT — LLM to fill in evidence from profile files

---

> **Clinical Note**: Requires ≥5 criteria from A1–A9, including A1 or A2.
> Duration: ≥2 weeks. Must cause significant distress or functional impairment.
> Exclude: manic/hypomanic episodes, substances, medical condition.

---

## Criterion Checklist

| ID | Criterion | Status | Evidence from Profile |
|----|-----------|--------|----------------------|
"""

TEMPLATE_ROW = "| {id} | {en} | [ ] NOT_ASSESSED | _(fill from darkness/traumas.md / psychology/formulation.md)_ |\n"

TEMPLATE_FOOTER = """
---

## Diagnostic Summary

- **Criteria met**: ___ / 9
- **A1 or A2 present**: YES / NO
- **Duration met (≥2 weeks)**: YES / NO / UNCLEAR
- **Functional impairment**: YES / NO / UNCLEAR
- **Exclusion criteria cleared**: YES / NO / UNCLEAR

**Provisional diagnosis**: _(LLM judgment)_

**Severity**: Mild / Moderate / Severe / N/A

**Confidence**: HIGH / MEDIUM / LOW

**Evidence gaps** (profile files that need more detail):
- _(list files)_

---
_Template generated by lucas-crisis-assess/generate-dsm5-mdd-checklist-template.py_
"""


def main():
    parser = argparse.ArgumentParser(
        description="Generate DSM-5 MDD checklist markdown template for a character"
    )
    parser.add_argument("--character", required=True, help="Character alias (hieu, hoa, chien)")
    parser.add_argument("--output", help="Output file path (default: stdout)")
    args = parser.parse_args()

    slug = resolve_character(args.character)
    display = CHAR_DISPLAY.get(slug, slug)
    today = date.today().strftime("%d/%m/%Y")

    content = TEMPLATE_HEADER.format(character=display, date=today)
    for crit_id, en_text, vi_text in DSM5_MDD_CRITERIA:
        content += f"| {crit_id} | **{en_text}** / {vi_text} | [ ] NOT_ASSESSED | _(fill from darkness/traumas.md / psychology/formulation.md)_ |\n"
    content += TEMPLATE_FOOTER

    if args.output:
        from pathlib import Path
        Path(args.output).write_text(content, encoding="utf-8")
        print(f"Template written to: {args.output}")
    else:
        print(content)


if __name__ == "__main__":
    main()
